services:
  mongodb:
    image: mongo:latest
    container_name: gaming-library-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db

  init-db:
    build:
      context: .
      dockerfile: Dockerfile.init
    container_name: gaming-library-init-db
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://admin:password@gaming-library-mongodb:27017/gaming-library?authSource=admin

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: gaming-library-backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://admin:password@gaming-library-mongodb:27017/gaming-library?authSource=admin
      - NODE_ENV=development
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules

volumes:
  mongodb_data: